language: node_js

node_js:
  - "10"

install:
  - yarn --frozen-lockfile

script:
  - yarn run lint
  - yarn run test

after_success:
  - yarn run coveralls

deploy:
  provider: script
  skip_cleanup: true
  script: ./travis-deploy.sh
  on:
    tags: true
